# Site Info
title:              "Yating Zou"
description:        " "
author_name:        "Yating Zou" # change this to your name
# Get logo url from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://yatingz205.github.io # main url
permalink:          /:title # Post permalink
timezone:           America/New-York # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        #33b8ff
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain

collections:
  research:
    output: true
    permalink: /research/:name
  project:
    output: true
    permalink: /project/:name
  blog:
    output: true
    permalink: /blog/:name

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      type:         "research"
    values:
      layout:       "research-post"
  -
    scope:
      type:         "project"
    values:
      layout:       "post"
  -
    scope:
      type:         "misc"
    values:
      layout:       "post"
